import Head from "next/head";
import Header from "./header";

import styles from "../styles/layout.module.css";
import { ReactNode } from "react";

type LayoutProps = {
  children: ReactNode;
  isProjectPage?: boolean;
};

export default function Layout({ children, isProjectPage }: LayoutProps) {
  let mainClassName = styles.main;

  if (isProjectPage) {
    mainClassName = `${styles.main} ${styles.project}`;
  }

  return (
    <div className={styles.layout}>
      <Head>
        <title>태양의 Curriculum Vitae | ttgu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={mainClassName}>{children}</main>
    </div>
  );
}
